export enum Permission {
  USER_READ = "USER_READ",
  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",
  COMPANY_READ = "COMPANY_READ",
  COMPANY_UPDATE = "COMPANY_UPDATE",
  SERVICE_CREATE = "SERVICE_CREATE",
  SERVICE_DELETE = "SERVICE_DELETE",
}
